name: Azure Static Web Apps CI/CD (Deprecated)

on:
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deprecated workflow. Use azure-static-web-apps-nextjs.yml instead."
