# ACTIVE Azure Static Web Apps workflow for this repository.
# This is the ONLY workflow that deploys the site.
# It builds the Next.js project with pnpm, then uploads the .next output.
# If you ever want Azure to perform the build itself ("Azure-managed build"),
# you can: (1) remove the Build step, (2) remove skip_app_build, and (3) optionally add app_build_command.
# For now, this explicit local build is simple and reliable.
name: Azure Static Web Apps CI/CD (Next.js)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack (pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@9.1.0 --activate

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build (Next.js)
        run: pnpm build
        env:
          NEXT_TELEMETRY_DISABLED: 1
          RESEND_API_KEY: 'build-time-placeholder'  # Actual key comes from Azure env vars at runtime

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_HILL_05871DB03 }}
          action: upload
          app_location: '/'
          api_location: ''
          output_location: '.next'
          skip_app_build: true  # We've already built

  close_pr_env:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_HILL_05871DB03 }}
          action: close
          app_location: ''
